name: Play With Docker Training
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..3
incremental: true
permalink: pretty
safe: false
lsi: false
url: https://training.play-with-docker.com
githuburl: https://github.com/play-with-docker/training
docs: no
description: >
  Train with Docker applications in the browser using Play With Docker! 
default-image: docker-logo.png
built-by: PWD Team
copyright:
   name: Docker, Inc.
   link: 'https://docker.com'

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      defaultassignee: manomarks
      toc_min: 2
      toc_max: 3
      tree: true
facebook: https://www.facebook.com/docker.run
twitter: https://twitter.com/@docker
github: https://github.com/play-with-docker/play-with-docker.github.io

#facebook like box
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/docker.run/
fb-page-title: Docker

sass:
  style: compressed

paginate: 6
paginate_path: /page:num/